.PHONY: clean All

All:
	@echo "----------Building project:[ function1 - Debug ]----------"
	@cd "function1" && "$(MAKE)" -f  "function1.mk"
clean:
	@echo "----------Cleaning project:[ function1 - Debug ]----------"
	@cd "function1" && "$(MAKE)" -f  "function1.mk" clean
